language: php

php:
  - 8.0

env:
  - DB=mysql:8.0

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'homestead'@'localhost';"
  - composer self-update && composer install -n --prefer-dist --no-scripts
  - php artisan optimize

script:
  - ./vendor/bin/phpunit
